name: Generate Datas
on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"
  workflow_dispatch:
jobs:
  build:
    name: Full-year calendar
    runs-on: ubuntu-latest
    steps:
      # Green Towers
      - uses: lowlighter/metrics@latest
        id: tower-gif
  
        with:
          github_user_name: paramsgit
          svg_out_path: dist/github-contribution-grid-tower.svg
          filename: metrics.plugin.isocalendar.fullyear.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
