name: Generate Datas
on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"
  workflow_dispatch:
jobs:
  build:
    name: Full-year calendar
    runs-on: ubuntu-latest
    steps:
      # Green Towers
      - uses: lowlighter/metrics@latest
        id: tower-gif
  
        with:
          filename: metrics.plugin.isocalendar.fullyear.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
